from app import db

# Player Class
class Player(db.Model):

    __tablename__ = "players"
    __table_args__ = {"schema": "nba_data"}
        
    team_id = db.Column(db.Integer, nullable=False)
    season = db.Column(db.Integer, nullable=False)
    league_id = db.Column(db.Integer)
    player = db.Column(db.String(100), nullable=False)
    nickname = db.Column(db.String(100))
    player_slug = db.Column(db.String(100))
    num = db.Column(db.Integer)
    pos = db.Column(db.String(10))
    height = db.Column(db.String(20))
    weight = db.Column(db.Integer)
    birth_date = db.Column(db.String(50))
    age = db.Column(db.Numeric(5, 1)) 
    experience = db.Column(db.String(20))
    school = db.Column(db.String(100))
    player_id = db.Column(db.Integer, primary_key=True, nullable=False)
    how_acquired = db.Column(db.String(200))

class Game(db.Model):
    __tablename__ = "games"
    __table_args__ = {"schema": "nba_data"}

    id = db.Column(db.Integer, primary_key=True, nullable=False)
    season_id = db.Column(db.Text)
    team_id = db.Column(db.BigInteger)
    team_abbreviation = db.Column(db.Text)
    team_name = db.Column(db.Text)
    game_id = db.Column(db.Text)
    game_date = db.Column(db.Text)
    matchup = db.Column(db.Text)
    wl = db.Column(db.Text)
    min = db.Column(db.BigInteger)
    fgm = db.Column(db.BigInteger)
    fga = db.Column(db.BigInteger)
    fg_pct = db.Column(db.Double)
    fg3m = db.Column(db.BigInteger)
    fg3a = db.Column(db.BigInteger)
    fg3_pct = db.Column(db.Double)
    ftm = db.Column(db.BigInteger)
    fta = db.Column(db.BigInteger)
    ft_pct = db.Column(db.Double)
    oreb = db.Column(db.BigInteger)
    dreb = db.Column(db.BigInteger)
    reb = db.Column(db.BigInteger)
    ast = db.Column(db.BigInteger)
    stl = db.Column(db.BigInteger)
    blk = db.Column(db.BigInteger)
    tov = db.Column(db.BigInteger)
    pf = db.Column(db.BigInteger)
    pts = db.Column(db.BigInteger)
    plus_minus = db.Column(db.BigInteger)
    video_available = db.Column(db.BigInteger)
    

class Totals(db.Model):
    __tablename__ = "totals"
    __table_args__ = {"schema": "nba_data"}

    player_id          = db.Column(db.BigInteger, primary_key=True, nullable=False)
    display_fi_last    = db.Column(db.Text)
    jersey_num         = db.Column(db.Text)
    gp                 = db.Column(db.BigInteger)
    gs                 = db.Column(db.BigInteger)
    actual_minutes     = db.Column(db.BigInteger)
    actual_seconds     = db.Column(db.BigInteger)
    fg                 = db.Column(db.BigInteger)
    fga                = db.Column(db.BigInteger)
    fg_pct             = db.Column(db.Float)
    fg3                = db.Column(db.BigInteger)
    fg3a               = db.Column(db.BigInteger)
    fg3_pct            = db.Column(db.Float)
    ft                 = db.Column(db.BigInteger)
    fta                = db.Column(db.BigInteger)
    ft_pct             = db.Column(db.Float)
    off_reb            = db.Column(db.BigInteger)
    def_reb            = db.Column(db.BigInteger)
    tot_reb            = db.Column(db.BigInteger)
    ast                = db.Column(db.BigInteger)
    pf                 = db.Column(db.BigInteger)
    dq                 = db.Column(db.BigInteger)
    stl                = db.Column(db.BigInteger)
    turnovers          = db.Column(db.BigInteger)
    blk                = db.Column(db.BigInteger)
    pts                = db.Column(db.BigInteger)
    max_actual_minutes = db.Column(db.BigInteger)
    max_actual_seconds = db.Column(db.BigInteger)
    max_reb            = db.Column(db.BigInteger)
    max_ast            = db.Column(db.BigInteger)
    max_stl            = db.Column(db.BigInteger)
    max_turnovers      = db.Column(db.BigInteger)
    max_blk            = db.Column(db.BigInteger)
    max_pts            = db.Column(db.BigInteger)
    avg_actual_minutes = db.Column(db.Text)
    avg_actual_seconds = db.Column(db.Float)
    avg_tot_reb        = db.Column(db.Float)
    avg_ast            = db.Column(db.Float)
    avg_stl            = db.Column(db.Float)
    avg_turnovers      = db.Column(db.Float)
    avg_blk            = db.Column(db.Float)
    avg_pts            = db.Column(db.Float)
    per_min_tot_reb    = db.Column(db.Float)
    per_min_ast        = db.Column(db.Float)
    per_min_stl        = db.Column(db.Float)
    per_min_turnovers  = db.Column(db.Float)
    per_min_blk        = db.Column(db.Float)
    per_min_pts        = db.Column(db.Float)


class GameByGame(db.Model):
    __tablename__ = "game_by_game"
    __table_args__ = {"schema": "nba_data"}

    id             = db.Column(db.BigInteger, primary_key=True, nullable=False)
    player_id      = db.Column(db.BigInteger, db.ForeignKey("nba_data.totals.player_id"))
    date_est       = db.Column(db.Text)
    visitor_team   = db.Column(db.Text)
    home_team      = db.Column(db.Text)
    gp             = db.Column(db.BigInteger)
    gs             = db.Column(db.BigInteger)
    actual_minutes = db.Column(db.BigInteger)
    actual_seconds = db.Column(db.BigInteger)
    fg             = db.Column(db.BigInteger)
    fga            = db.Column(db.BigInteger)
    fg_pct         = db.Column(db.Float)
    fg3            = db.Column(db.BigInteger)
    fg3a           = db.Column(db.BigInteger)
    fg3_pct        = db.Column(db.Float)
    ft             = db.Column(db.BigInteger)
    fta            = db.Column(db.BigInteger)
    ft_pct         = db.Column(db.Float)
    off_reb        = db.Column(db.BigInteger)
    def_reb        = db.Column(db.BigInteger)
    tot_reb        = db.Column(db.BigInteger)
    avg_tot_reb    = db.Column(db.Float)
    ast            = db.Column(db.BigInteger)
    pf             = db.Column(db.BigInteger)
    dq             = db.Column(db.BigInteger)
    stl            = db.Column(db.BigInteger)
    turnovers      = db.Column(db.BigInteger)
    blk            = db.Column(db.BigInteger)
    pts            = db.Column(db.BigInteger)
    avg_pts        = db.Column(db.Float)
    date_string    = db.Column(db.Text)

